### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by lightsprint09** [automerge/automerge-swift#139]
The old automerge-swift stored Timestamp in milliseconds (not sure why), resulting in wrong resulting Dates when importing it with the new automerge-swift. Any idea we can mitigate this?

**Comment by heckj** [comment]
It would require changes to the Automerge core - I'm uncertain on why it changed, exactly. I considered a transformation that preserved a Double (Date's internal TimeInterval type) from 1970 epoch, but in some ways that's even more oblique, and clearly doesn't map to the internal Automerge representation which has less granular resolution, so it didn't seem to offer any cross-platform benefit.

@alexjg - any insight into the change in internal Automerge representation of Value.Timestamp?

**Comment by lightsprint09** [comment]
I guess the old auto merge implemented it wrong

**Comment by alexjg** [comment]
I think this is actually a case where we got it wrong in the Swift implementation. The rest of the automerge implementations use _milliseconds_ since the epoch.

**Comment by alexjg** [comment]
Ideally we would update the swift implementation (which I think just corresponds to changing the documentation?).

**Comment by lightsprint09** [comment]
So the new implementation is missing this [piece of code](https://github.com/automerge/automerge-swift-archived/blob/4e57b78ea932c4abdf85002c0d2cde99c59614d7/Source/applyPatch.swift#L326)?
